#!/bin/bash
wget -O /www/xderm/xderm-mini https://raw.githubusercontent.com/Channel-Gratisan/xderm-mini_GUI/main/xderm-mini -q
wget -O /www/xderm/index.php https://raw.githubusercontent.com/Channel-Gratisan/xderm-mini_GUI/main/index.php -q
